<?php

namespace PostparcBundle\Repository;

/**
 * AttachmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function forceDelete($id)
    {
        if ($id) {
            $dql = $this->createQueryBuilder('c')->delete('PostparcBundle\Entity\Attachment a')->where('a.id=' . $id);

            return $query = $this->_em->createQuery($dql)->execute();
        } else {
            return true;
        }
    }
}
