<?php

namespace PostparcBundle\Repository;

/**
 * DocumentTemplateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTemplateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * search query.
     *
     * @param type $filter
     * @param type $entityId
     * @param type $show_SharedContents
     *
     * @return type
     */
    public function search($filter, $entityId = null, $show_SharedContents = true, $orderBy = '', $orderDirection = 'ASC')
    {
        $dql = $this->createQueryBuilder('dt')->select('dt')
                ->where('dt.deletedAt IS NULL')
                ->leftJoin('dt.createdBy', 'c');

        (array_key_exists('name', $filter) && $filter['name']) ? $dql->andwhere("dt.name LIKE '%" . $filter['name'] . "%'") : '';

        if ($entityId !== null) {
            $dql->leftJoin('dt.entity', 'entity');
            if ($show_SharedContents) {
                $dql->andWhere('entity.id=' . $entityId . ' OR (entity.id!=' . $entityId . ' AND dt.isShared=1)');
            } else {
                $dql->andWhere('entity.id=' . $entityId . '');
            }
        }
        
        if (array_key_exists('createdBy', $filter) ) {
            $createdByUser = $filter['createdBy'];
            $dql->andWhere('c.id='.$createdByUser->getId());
        }
        
        if (array_key_exists('currentUser', $filter) ) {
            $currentUser = $filter['currentUser'];            
            $dql->andWhere('(dt.isPrivate!=1 OR (dt.isPrivate=1 AND c.id='.$currentUser->getId().'))');
        }
        
        if('' !== $orderBy){
            $dql->orderby($orderBy, $orderDirection);
        }

        return $query = $this->_em->createQuery($dql);
    }

    /**
     * list all active documentTemplates.
     *
     * @param type $entityId
     * @param type $show_SharedContents
     *
     * @return type
     */
    public function getActiveDocumentTemplates($entityId = null, $show_SharedContents = true, $onlymailable = false, $currentUser= null)
    {
        $dql = $this->createQueryBuilder('dt')->select('dt')
            ->where('dt.deletedAt IS NULL')
            ->andWhere('dt.isActive=1')
            ->leftJoin('dt.createdBy', 'c')    
            ->orderby('dt.name', 'DESC');

        if ($entityId !== null) {
            $dql->leftJoin('dt.entity', 'entity');
            if ($show_SharedContents) {
                $dql->andWhere('entity.id=' . $entityId . ' OR (entity.id!=' . $entityId . ' AND dt.isShared=1)');
            } else {
                $dql->andWhere('entity.id=' . $entityId . '');
            }
        }
        if ($onlymailable) {
            $dql->andWhere('dt.mailable=1');
        }
        
        if($currentUser) {
            $dql->andWhere('(dt.isPrivate!=1 OR (dt.isPrivate=1 AND c.id='.$currentUser->getId().'))');
        }

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }

    /**
     * query for massive delete.
     *
     * @param type $ids
     * @param type $entityId
     */
    public function batchDelete($ids = null, $entityId = null, $currentUser = null)
    {
        if ($ids !== null) {
            // first query for hard delete
            $hardDql = $this->createQueryBuilder('dt')->delete('PostparcBundle\Entity\DocumentTemplate dt')->where('dt.id IN (' . implode(',', $ids) . ')');
            $hardDql->andWhere('dt.deletedAt IS NOT NULL');

            // second query for soft delete
            $now = new \Datetime();
            $softDql = $this->createQueryBuilder('p')->update('PostparcBundle\Entity\DocumentTemplate dt')
                    ->set('dt.deletedAt', "'" . $now->format('Y-m-d H:i:s') . "'")
                    ->where('dt.id IN (' . implode(',', $ids) . ')');

            if ($entityId !== null) {
                $hardDql->andWhere('dt.entity=' . $entityId);
                $softDql->andWhere('dt.entity=' . $entityId);
            }

            if ($currentUser) {
                $softDql->set('dt.deletedBy', $currentUser->getId());
            }

            //queries execution
            $this->_em->createQuery($hardDql)->execute();
            $this->_em->createQuery($softDql)->execute();
        }
    }

    /**
     * query for massive restore.
     *
     * @param type $ids
     * @param type $entityId
     */
    public function batchRestore($ids = null, $entityId = null)
    {
        if ($ids !== null) {
            $dql = $this->createQueryBuilder('dt')->update('PostparcBundle\Entity\DocumentTemplate dt')
                    ->set('dt.deletedAt', 'NULL')
                    ->set('dt.deletedBy', 'NULL')
                    ->where('dt.id IN (' . implode(',', $ids) . ')');

            if ($entityId !== null) {
                $dql->andWhere('dt.entity=' . $entityId);
            }
            $this->_em->createQuery($dql)->execute();
        }
    }

    /**
     * list of trashed elements.
     *
     * @param type $entityId
     *
     * @return type
     */
    public function getTrashedElements($entityId = null)
    {
        $dql = $this->createQueryBuilder('dt')->select('dt')
                ->where('dt.deletedAt IS NOT NULL')
                ->orderby('dt.name', 'ASC');
        if ($entityId !== null) {
            $dql->andWhere('dt.entity=' . $entityId);
        }
        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }

    /**
     * autocomplete query.
     *
     * @param type $q
     * @param type $entityId
     * @param type $show_SharedContents
     *
     * @return type
     */
    public function autoComplete($q, $entityId = null, $show_SharedContents = true)
    {
        $dql = $this->createQueryBuilder('dt')
            ->where('dt.deletedAt IS NULL')
            ->orderby('dt.name', 'ASC')
            ;
        if ($q) {
            $dql->andWhere("dt.name LIKE '%" . $q . "%'");
        }
        if ($entityId !== null) {
            $dql->leftJoin('dt.entity', 'entity');
            if ($show_SharedContents) {
                $dql->andWhere('entity.id=' . $entityId . ' OR (entity.id!=' . $entityId . ' AND dt.isShared=1)');
            } else {
                $dql->andWhere('entity.id=' . $entityId . '');
            }
        }
        $query = $this->_em->createQuery($dql);
        $query->setMaxResults(30);

        return $query->getResult();
    }
}
