<?php

namespace PostparcBundle\Repository;

/**
 * EntityCoordinateDistanceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityCoordinateDistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
