<?php

namespace PostparcBundle\Repository;

/**
 * EventRepresentationsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepresentationsRepository extends \Doctrine\ORM\EntityRepository
{
}
