<?php

namespace PostparcBundle\Repository;

/**
 * EventPersonsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPersonsRepository extends \Doctrine\ORM\EntityRepository
{
}
