<?php

namespace PostparcBundle\Repository;

/**
 * EventPfosRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPfosRepository extends \Doctrine\ORM\EntityRepository
{
}
