<?php

namespace PostparcBundle\Repository;

/**
 * HelpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRepository extends TranslatableRepository
{
    public function search($filter)
    {
        $dql = $this->createQueryBuilder('c')->select('c');

        (array_key_exists('name', $filter) && $filter['name']) ? $dql->andwhere("c.name LIKE '%" . $filter['name'] . "%'") : '';

        //return $this->_em->createQuery($dql);
        return $this->getResult($dql);
    }

    public function batchDelete($ids = null)
    {
        if ($ids) {
            $dql = $this->createQueryBuilder('c')->delete('PostparcBundle\Entity\Help c')->where('c.id IN (' . implode(',', $ids) . ')');

            return $query = $this->_em->createQuery($dql)->execute();
        }
    }
}
