<?php

namespace PostparcBundle\Repository;

/**
 * MailFooterRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailFooterRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($filter, $user = null)
    {
        $dql = $this->createQueryBuilder('mf')
                ->select('mf')->leftJoin('mf.user', 'u');

        (array_key_exists('name', $filter) && $filter['name']) ? $dql->andwhere("mf.name LIKE '%" . $filter['name'] . "%'") : '';
        (array_key_exists('user', $filter) && $filter['user']) ? $dql->andwhere("u.id = " . $filter['user']) : '';

        if ($user) {
            if (!$user->hasRole('ROLE_ADMIN')) {
                $dql->andWhere('u.id=' . $user->getId());
            }
            if (!$user->hasRole('ROLE_SUPER_ADMIN')) {
                $dql->leftJoin('u.entity', 'e');
                $dql->andWhere('e.id=' . $user->getEntity()->getId());
            }
        }
        return $query = $this->_em->createQuery($dql);
    }

    public function batchDelete($ids = null)
    {
        if ($ids) {
            $dql = $this->createQueryBuilder('mf')->delete('PostparcBundle\Entity\MailFooter mf')->where('mf.id IN (' . implode(',', $ids) . ')');

            return $query = $this->_em->createQuery($dql)->execute();
        }
    }
}
