<?php

namespace PostparcBundle\Repository;

use Cocur\Slugify\Slugify;

/**
 * NatureOfRepresentationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureOfRepresentationRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($filter)
    {
        $slugify = new Slugify();
        $dql = $this->createQueryBuilder('n')->select('n');

        if (array_key_exists('name', $filter) && $filter['name']) {
            $slug = $slugify->slugify($filter['name'], '-');
            $dql->andwhere('n.slug LIKE \'%' . $slug . '%\'');
        }
        (array_key_exists('orderBy', $filter)) ? $dql->orderBy($filter['orderBy']['field'], $filter['orderBy']['direction']) : '';

        return $query = $this->_em->createQuery($dql);
    }

    public function batchDelete($ids = null, $entityId = null)
    {
        if ($ids) {
            $dql = $this->createQueryBuilder('n')->delete('PostparcBundle\Entity\NatureOfRepresentation n')->where('n.id IN (' . implode(',', $ids) . ')');

            if ($entityId) {
                $dql->andWhere('n.entity=' . $entityId);
            }

            //queries execution
            $this->_em->createQuery($dql)->execute();
        }
    }

    public function autoComplete($q, $page_limit = 30, $page = null)
    {
        $dql = $this->createQueryBuilder('n')
            ->orderby('n.name', 'ASC')
        ;
        if ($q) {
            $slugify = new Slugify();
            $slug = $slugify->slugify($q, '-');
            $dql->andwhere('n.slug LIKE \'%' . $slug . '%\'');
        }
        $query = $this->_em->createQuery($dql);
        $query->setMaxResults($page_limit);
        if ($page) {
            $query->setFirstResult(($page - 1) * $page_limit);
        }

        return $query->getResult();
    }
}
