<?php

namespace PostparcBundle\Repository;

/**
 * NoteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getObjectNotes($className, $objectId, $currentUserID)
    {
        $dql = $this->createQueryBuilder('n')->select('n')
                ->leftJoin('n.createdBy', 'u')
                ->where("n.className='" . $className . "'")
                ->andwhere('n.objectId=' . $objectId)
                ->andwhere('u.id=' . $currentUserID . ' OR (u.id!=' . $currentUserID . ' AND n.isPrivate!=1)')
                ->orderBy('n.date', 'DESC')
                ;

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }
}
