<?php

namespace PostparcBundle\Repository;

/**
 * OrganizationLinkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationLinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrganisationHorizontalLink($organisationId, $readerLimitations = null)
    {
        $dql = $this->createQueryBuilder('ol')
                ->leftJoin('ol.organizationOrigin', 'origin')
                ->leftJoin('ol.organizationLinked', 'linked')
                ->where('ol.linkType IN (2,3)')
                ->andWhere('origin.id=' . $organisationId . ' or linked.id=' . $organisationId)
        ;

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }

    public function getOrganisationParents($organisationId, $readerLimitations = null)
    {
        $dql = $this->createQueryBuilder('ol')
                ->leftJoin('ol.organizationOrigin', 'origin')
                ->where('ol.linkType IN (1)')
                ->andWhere('origin.id=' . $organisationId)
        ;

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }

    public function getOrganisationChildreens($organisationId, $readerLimitations = null)
    {
        $dql = $this->createQueryBuilder('ol')
                ->leftJoin('ol.organizationLinked', 'linked')
                ->where('ol.linkType IN (1)')
                ->andWhere('linked.id=' . $organisationId)
        ;

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }
}
