<?php

namespace PostparcBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Cocur\Slugify\Slugify;

/**
 * OrganizationTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationTypeRepository extends NestedTreeRepository
{
    public function search($filter)
    {
        $dql = $this->createQueryBuilder('ot')->select('ot.id, ot.level, ot.name, ot.root, ot.lft, ot.rgt, ot.slug, u.id as creatorId, u.username')
            ->leftJoin('ot.createdBy', 'u')
            ->orderBy('ot.root, ot.lft', 'ASC')
        ;
        $slugify = new Slugify();
        if (isset($filter['name']) && '' != $filter['name']) {
            $slug = $slugify->slugify($filter['name'], '-');
            $dql->andwhere('ot.slug LIKE \'%' . $slug . '%\'');
        }
        (array_key_exists('updatedBy', $filter) && $filter['updatedBy']) ? $dql->andwhere("ot.updatedBy = '" . $filter['updatedBy'] . "'") : '';

        return $query = $this->_em->createQuery($dql);
    }

    public function batchDelete($ids = null, $entityId = null)
    {
        if ($ids) {
            // first query for hard delete
            $dql = $this->createQueryBuilder('ot')->delete('PostparcBundle\Entity\OrganizationType ot')->where('ot.id IN (' . implode(',', $ids) . ')');

            if ($entityId) {
                $dql->andWhere('ot.entity=' . $entityId);
            }

            //queries execution
            $this->_em->createQuery($dql)->execute();
        }
    }

    public function autoComplete($q, $page_limit = 60, $page = null)
    {
        $dql = $this->createQueryBuilder('ot')
            ->orderby('ot.name', 'ASC')
        ;
        if ($q) {
            $slugify = new Slugify();
            $slug = $slugify->slugify($q, '-');
            $dql->andwhere('ot.slug LIKE \'%' . $slug . '%\'');
        }
        $query = $this->_em->createQuery($dql);
        $query->setMaxResults($page_limit);
        if ($page) {
            $query->setFirstResult(($page - 1) * $page_limit);
        }

        return $query->getResult();
    }
}
