<?php

namespace PostparcBundle\Repository;

use Cocur\Slugify\Slugify;

/**
 * ProfessionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($filter)
    {
        $slugify = new Slugify();
        $dql = $this->createQueryBuilder('p')->select('p');

        if (array_key_exists('name', $filter) && $filter['name']) {
            $slug = $slugify->slugify($filter['name'], '-');
            $dql->andwhere('p.slug LIKE \'%' . $slug . '%\'');
        }

        return $query = $this->_em->createQuery($dql);
    }

    public function batchDelete($ids = null, $entityId = null)
    {
        if ($ids) {
            $dql = $this->createQueryBuilder('p')->delete('PostparcBundle\Entity\Profession p')->where('p.id IN (' . implode(',', $ids) . ')');

            if ($entityId) {
                $dql->andWhere('p.entity=' . $entityId);
            }
            //queries execution
            $this->_em->createQuery($dql)->execute();
        }
    }

    public function autoComplete($q, $page_limit = 30, $page = null)
    {
        $dql = $this->createQueryBuilder('p')
            ->orderby('p.name', 'ASC')
        ;
        if ($q) {
            $slugify = new Slugify();
            $slug = $slugify->slugify($q, '-');
            $dql->andwhere('p.slug LIKE \'%' . $slug . '%\'');
        }
        $query = $this->_em->createQuery($dql);
        $query->setMaxResults($page_limit);
        if ($page) {
            $query->setFirstResult(($page - 1) * $page_limit);
        }

        return $query->getResult();
    }
}
