<?php

namespace PostparcBundle\Repository;

/**
 * ReaderLimitationsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReaderLimitationRepository extends \Doctrine\ORM\EntityRepository
{
}
