<?php

namespace PostparcBundle\Repository;

/**
 * UserCoordinateDistanceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCoordinateDistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
