imports:
    - { resource: config.yml }

framework:
    cache:
        prefix_seed: postparc
        app: cache.adapter.redis
        default_redis_provider: 'redis://localhost'
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

doctrine:
    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc        
        metadata_cache_driver: redis
        result_cache_driver: redis
        query_cache_driver: redis
#        metadata_cache_driver: array
#        result_cache_driver: array
#        query_cache_driver: array

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
            
