<?php

namespace PostparcApiBundle\Repository;

/**
 * AuthTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserActiveAuthToken($user)
    {
        // recherche si AuthToken encore actif pour ce user dans la base
        $date = new \DateTime();
        $date->sub(new \DateInterval('PT' . (12 * 3600) . 'S'));

        $dql = $this->createQueryBuilder('at')->select('at')
                ->leftJoin('at.user', 'u')
                ->where('u.id=' . $user->getId())
                ->andWhere('at.createdAt >=\'' . $date->format('Y-m-d H:i:s') . '\'');


        $query = $this->_em->createQuery($dql);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function findAuthTokenByValue($value)
    {
        $dql = $this->createQueryBuilder('at')
                ->select('at')
                ->andWhere('at.value=\'' . $value . '\'');
        $query = $this->_em->createQuery($dql);

        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
